# Generated by Django 4.1.13 on 2023-12-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe_Laying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('start_node', models.CharField(max_length=20)),
                ('stop_node', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('diameter_id', models.IntegerField()),
                ('diameter_od', models.IntegerField()),
                ('material', models.CharField(max_length=20)),
                ('laying_length', models.CharField(blank=True, max_length=20, null=True)),
                ('balance_laying', models.IntegerField()),
            ],
            options={
                'db_table': 'pipe_layings',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'site_details',
            },
        ),
    ]
